--
-- PostgreSQL database dump
--

\restrict 6VVB9cLz2NVNWEsefUYY9wwSxZYoPtxvtD2yThU5dvYFXsgbdwz7RmEP9HKEwhY

-- Dumped from database version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.10 (Ubuntu 16.10-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO vehicleuser2;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO vehicleuser2;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO vehicleuser2;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authentication_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.authentication_customuser OWNER TO vehicleuser2;

--
-- Name: authentication_customuser_groups; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authentication_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_groups OWNER TO vehicleuser2;

--
-- Name: authentication_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.authentication_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.authentication_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_user_permissions; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authentication_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_user_permissions OWNER TO vehicleuser2;

--
-- Name: authentication_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.authentication_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_manager; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authentication_manager (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_manager OWNER TO vehicleuser2;

--
-- Name: authentication_manager_enterprises; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authentication_manager_enterprises (
    id bigint NOT NULL,
    manager_id bigint NOT NULL,
    enterprise_id integer NOT NULL
);


ALTER TABLE public.authentication_manager_enterprises OWNER TO vehicleuser2;

--
-- Name: authentication_manager_enterprises_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.authentication_manager_enterprises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_manager_enterprises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_manager_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.authentication_manager ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO vehicleuser2;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO vehicleuser2;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO vehicleuser2;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO vehicleuser2;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO vehicleuser2;

--
-- Name: vehicle_brand; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.vehicle_brand (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    vehicle_type character varying(20) NOT NULL,
    fuel_tank_capacity smallint NOT NULL,
    cargo_capacity smallint,
    seating_capacity smallint NOT NULL,
    CONSTRAINT vehicle_brand_cargo_capacity_check CHECK ((cargo_capacity >= 0)),
    CONSTRAINT vehicle_brand_fuel_tank_capacity_check CHECK ((fuel_tank_capacity >= 0)),
    CONSTRAINT vehicle_brand_id_check CHECK ((id >= 0)),
    CONSTRAINT vehicle_brand_seating_capacity_check CHECK ((seating_capacity >= 0))
);


ALTER TABLE public.vehicle_brand OWNER TO vehicleuser2;

--
-- Name: vehicle_driver; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.vehicle_driver (
    id bigint NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    license_number character varying(20) NOT NULL,
    salary numeric(10,2) NOT NULL,
    enterprise_id integer NOT NULL
);


ALTER TABLE public.vehicle_driver OWNER TO vehicleuser2;

--
-- Name: vehicle_driver_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.vehicle_driver ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_driver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_drivervehicle; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.vehicle_drivervehicle (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    driver_id bigint NOT NULL,
    vehicle_id integer NOT NULL
);


ALTER TABLE public.vehicle_drivervehicle OWNER TO vehicleuser2;

--
-- Name: vehicle_drivervehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.vehicle_drivervehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_drivervehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_enterprise; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.vehicle_enterprise (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    address character varying(255) NOT NULL,
    phone character varying(20) NOT NULL
);


ALTER TABLE public.vehicle_enterprise OWNER TO vehicleuser2;

--
-- Name: vehicle_enterprise_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.vehicle_enterprise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_enterprise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle_vehicle; Type: TABLE; Schema: public; Owner: vehicleuser2
--

CREATE TABLE public.vehicle_vehicle (
    id integer NOT NULL,
    car_number character varying(15) NOT NULL,
    price numeric(12,2) NOT NULL,
    year smallint NOT NULL,
    mileage integer NOT NULL,
    fuel_type character varying(20) NOT NULL,
    transmission character varying(20) NOT NULL,
    color character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    brand_id integer NOT NULL,
    enterprise_id integer NOT NULL,
    CONSTRAINT vehicle_vehicle_mileage_check CHECK ((mileage >= 0)),
    CONSTRAINT vehicle_vehicle_year_check CHECK ((year >= 0))
);


ALTER TABLE public.vehicle_vehicle OWNER TO vehicleuser2;

--
-- Name: vehicle_vehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: vehicleuser2
--

ALTER TABLE public.vehicle_vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_vehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Бренд	6	add_brand
22	Can change Бренд	6	change_brand
23	Can delete Бренд	6	delete_brand
24	Can view Бренд	6	view_brand
25	Can add Водитель	7	add_driver
26	Can change Водитель	7	change_driver
27	Can delete Водитель	7	delete_driver
28	Can view Водитель	7	view_driver
29	Can add Предприятие	8	add_enterprise
30	Can change Предприятие	8	change_enterprise
31	Can delete Предприятие	8	delete_enterprise
32	Can view Предприятие	8	view_enterprise
33	Can add Назначение водителя автомобилю	9	add_drivervehicle
34	Can change Назначение водителя автомобилю	9	change_drivervehicle
35	Can delete Назначение водителя автомобилю	9	delete_drivervehicle
36	Can view Назначение водителя автомобилю	9	view_drivervehicle
37	Can add Автомобиль	10	add_vehicle
38	Can change Автомобиль	10	change_vehicle
39	Can delete Автомобиль	10	delete_vehicle
40	Can view Автомобиль	10	view_vehicle
41	Can add user	11	add_customuser
42	Can change user	11	change_customuser
43	Can delete user	11	delete_customuser
44	Can view user	11	view_customuser
45	Can add Менеджер	12	add_manager
46	Can change Менеджер	12	change_manager
47	Can delete Менеджер	12	delete_manager
48	Can view Менеджер	12	view_manager
49	Can add Token	13	add_token
50	Can change Token	13	change_token
51	Can delete Token	13	delete_token
52	Can view Token	13	view_token
53	Can add Token	14	add_tokenproxy
54	Can change Token	14	change_tokenproxy
55	Can delete Token	14	delete_tokenproxy
56	Can view Token	14	view_tokenproxy
\.


--
-- Data for Name: authentication_customuser; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authentication_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, created_at) FROM stdin;
2	pbkdf2_sha256$1000000$0aMqY4koiv8RyDOZgws8jU$ilFRmecEgXZWcUoyaWWZbgsiqyqcTipQmA+aIU2oqdQ=	2025-10-23 16:20:45.215+07	f	manager1				t	t	2025-10-16 14:59:27+07	2025-10-16 14:59:27.501+07
4	pbkdf2_sha256$1000000$AInOsPxb023DJgoAkPFNM9$wYuAJ9byMg6kvkxZOekhK/L3rzw9q85wWBngH7CnKHI=	\N	f	manager2				f	t	2025-10-20 04:20:43.625+07	2025-10-20 04:20:44.456+07
5	pbkdf2_sha256$1000000$34c4QHHrSHY6BPtZme35fz$NSFREE4SWMFL0GEDmENvGFUYwwNKE//4XdS3bH1IC7I=	\N	f	test				f	t	2025-10-20 15:01:52.467+07	2025-10-20 15:01:53.33+07
1	pbkdf2_sha256$1000000$1t5ZgxGVK8Gpt0fEL4R71w$J5aNkpbHkAM7QXTILSrAx0PsbZcOWBoYkDY+cHJHWo0=	2025-10-28 15:32:47.293029+07	t	admin				t	t	2025-10-16 14:56:55.98+07	2025-10-16 14:56:55.98+07
\.


--
-- Data for Name: authentication_customuser_groups; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authentication_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: authentication_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authentication_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authentication_manager; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authentication_manager (id, user_id) FROM stdin;
1	2
2	4
\.


--
-- Data for Name: authentication_manager_enterprises; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authentication_manager_enterprises (id, manager_id, enterprise_id) FROM stdin;
1	1	1
2	1	2
3	1	15
4	2	2
5	2	3
6	2	6
7	2	15
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-16 14:59:27.503+07	2	manager1	1	[{"added": {}}]	11	1
2	2025-10-16 15:11:19.625+07	2	manager1	2	[{"changed": {"fields": ["Staff status"]}}]	11	1
3	2025-10-16 15:15:37.576+07	1	1, Рога и Копыта, Москва, Краснопрудная, +7 495 02-55-252	1	[{"added": {}}]	8	1
4	2025-10-16 15:15:50.531+07	1	manager1, 1 Рога и Копыта	1	[{"added": {}}]	12	1
5	2025-10-16 15:28:32.717+07	1	1, Иванов Иван, Рога и Копыта, 	1	[{"added": {}}]	7	1
6	2025-10-16 15:28:54.859+07	1	1, BMW, Легковой, 78 л., 1000 кг., 5	1	[{"added": {}}]	6	1
7	2025-10-16 15:29:26.046+07	1	1, ЕЕ453РН54, Рога и Копыта, 	1	[{"added": {}}]	10	1
8	2025-10-16 15:29:34.443+07	1	1, Иван Иванов (дополнительный) → 1, ЕЕ453РН54 	1	[{"added": {}}]	9	1
9	2025-10-16 18:10:32.347+07	3	test	1	[{"added": {}}]	11	1
10	2025-10-16 18:11:09.018+07	3	test	2	[{"changed": {"fields": ["Staff status"]}}]	11	1
11	2025-10-20 04:07:08.279+07	5	5, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	1
12	2025-10-20 04:07:08.279+07	4	4, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	1
13	2025-10-20 04:07:16.398+07	2	2, Русское авто, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u043f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u044f"]}}]	8	1
14	2025-10-20 04:07:27.709+07	3	3, Автодом, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u043f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u044f"]}}]	8	1
15	2025-10-20 04:07:58.179+07	2	2, Сергеев Сергей, Рога и Копыта, 	1	[{"added": {}}]	7	1
16	2025-10-20 04:08:21.586+07	3	3, Кузьмов Семён, Рога и Копыта, 	1	[{"added": {}}]	7	1
17	2025-10-20 04:08:39.875+07	4	4, Андреев Кирилл, Русское авто, 	1	[{"added": {}}]	7	1
18	2025-10-20 04:09:05.887+07	5	5, Петров Юрий, Русское авто, 	1	[{"added": {}}]	7	1
19	2025-10-20 04:09:38.257+07	6	6, Цирман Дмитрий, Русское авто, 	1	[{"added": {}}]	7	1
20	2025-10-20 04:09:58.887+07	7	7, Кириллов Андрей, Автодом, 	1	[{"added": {}}]	7	1
21	2025-10-20 04:10:20.935+07	8	8, Денисов Еким, Автодом, 	1	[{"added": {}}]	7	1
22	2025-10-20 04:10:47.393+07	9	9, Ирман Тимур, Автодом, 	1	[{"added": {}}]	7	1
23	2025-10-20 04:12:11.499+07	2	2, ПЕ345РИ65, Русское авто, 	1	[{"added": {}}]	10	1
24	2025-10-20 04:12:32.968+07	3	3, Н234ПП, Автодом, 	1	[{"added": {}}]	10	1
25	2025-10-20 04:12:44.009+07	2	2, ПЕ345РИ65, Русское авто, 	2	[{"changed": {"fields": ["\\u0421\\u0442\\u043e\\u0438\\u043c\\u043e\\u0441\\u0442\\u044c, \\u20bd"]}}]	10	1
26	2025-10-20 04:13:04.765+07	2	3, Семён Кузьмов (основной) → 1, ЕЕ453РН54 	1	[{"added": {}}]	9	1
27	2025-10-20 04:13:10.663+07	3	4, Кирилл Андреев (дополнительный) → 2, ПЕ345РИ65 	1	[{"added": {}}]	9	1
28	2025-10-20 04:13:16.853+07	4	7, Андрей Кириллов (дополнительный) → 3, Н234ПП 	1	[{"added": {}}]	9	1
29	2025-10-20 04:13:27.545+07	5	6, Дмитрий Цирман (основной) → 2, ПЕ345РИ65 	1	[{"added": {}}]	9	1
30	2025-10-20 04:20:44.458+07	4	manager2	1	[{"added": {}}]	11	1
31	2025-10-20 04:21:01.365+07	2	manager2, 2 Русское авто, 3 Автодом	1	[{"added": {}}]	12	1
32	2025-10-20 04:21:09.691+07	1	manager1, 1 Рога и Копыта, 2 Русское авто	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u044f"]}}]	12	1
33	2025-10-20 04:21:42.08+07	6	6, Тест, Москва, Адрес, 45634	1	[{"added": {}}]	8	2
34	2025-10-20 04:41:58.913+07	7	7, Тест1, Москва, Адрес, 34534	1	[{"added": {}}]	8	2
35	2025-10-20 05:10:41.932+07	10	10, ц45 235, Тест1, 	1	[{"added": {}}]	7	2
36	2025-10-20 05:11:01.186+07	8	8, цуеце, Тест1, 	1	[{"added": {}}]	10	2
37	2025-10-20 05:11:10.353+07	6	10, 235 ц45 (дополнительный) → 8, цуеце 	1	[{"added": {}}]	9	2
38	2025-10-20 05:11:28.388+07	2	manager2, 2 Русское авто, 3 Автодом, 6 Тест, 7 Тест1	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u044f"]}}]	12	1
39	2025-10-20 05:13:51.42+07	7	7, Тест1, Москва, Адрес, 34534	3		8	2
40	2025-10-20 05:19:41.815+07	12	12, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	2
41	2025-10-20 05:19:41.815+07	11	11, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	2
42	2025-10-20 05:19:41.815+07	10	10, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	2
43	2025-10-20 05:19:41.815+07	8	8, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	2
44	2025-10-20 05:19:56.776+07	9	9, A123BC77, Рога и Копыта, 	3		10	2
45	2025-10-20 05:22:26.82+07	13	13, Авто и машинки, Москва, ул. Новая, д. 1, +7 (383) 123-45-67	3		8	2
46	2025-10-20 05:25:42.924+07	10	10, A123BC77, Рога и Копыта, 	3		10	2
47	2025-10-20 15:01:35.412+07	3	test	3		11	1
48	2025-10-20 15:01:53.331+07	5	test	1	[{"added": {}}]	11	1
49	2025-10-20 19:25:58.636+07	12	12, ЕЕ453РН54, Рога и Копыта, 	1	[{"added": {}}]	10	2
50	2025-10-20 19:26:10.073+07	7	1, Иван Иванов (дополнительный) → 12, ЕЕ453РН54 	1	[{"added": {}}]	9	2
51	2025-10-20 19:27:16.423+07	13	13, ЕЕ453РН54, Рога и Копыта, 	1	[{"added": {}}]	10	2
52	2025-10-20 19:27:25.082+07	8	1, Иван Иванов (дополнительный) → 13, ЕЕ453РН54 	1	[{"added": {}}]	9	2
53	2025-10-20 19:36:26.579+07	14	14, ЕЕ453РН54, Рога и Копыта, 	1	[{"added": {}}]	10	2
54	2025-10-20 19:36:32.43+07	9	1, Иван Иванов (дополнительный) → 14, ЕЕ453РН54 	1	[{"added": {}}]	9	2
55	2025-10-21 17:02:27.163+07	15	15, Тест, ch, cfg, 4567567	1	[{"added": {}}]	8	2
56	2025-10-21 17:02:42.429+07	2	manager2, 2 Русское авто, 3 Автодом, 6 Тест, 15 Тест	2	[{"changed": {"fields": ["\\u041f\\u0440\\u0435\\u0434\\u043f\\u0440\\u0438\\u044f\\u0442\\u0438\\u044f"]}}]	12	1
57	2025-10-28 14:40:13.33+07	11	11, Андреев Дмитрий, Рога и Копыта, 	1	[{"added": {}}]	7	1
58	2025-10-28 14:40:25.272+07	12	12, Кузьмов Еким, Русское авто, 	1	[{"added": {}}]	7	1
59	2025-10-28 14:40:40.824+07	13	13, Ирман Кирилл, Автодом, 	1	[{"added": {}}]	7	1
60	2025-10-28 14:41:06.818+07	15	15, Е456АП, Рога и Копыта, 	1	[{"added": {}}]	10	1
61	2025-10-28 14:41:14.112+07	10	11, Дмитрий Андреев (дополнительный) → 14, ЕЕ453РН54 	1	[{"added": {}}]	9	1
62	2025-10-28 14:41:23.743+07	11	11, Дмитрий Андреев (основной) → 15, Е456АП 	1	[{"added": {}}]	9	1
63	2025-10-28 14:41:39.235+07	12	13, Кирилл Ирман (дополнительный) → 3, Н234ПП 	1	[{"added": {}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	vehicle	brand
7	vehicle	driver
8	vehicle	enterprise
9	vehicle	drivervehicle
10	vehicle	vehicle
11	authentication	customuser
12	authentication	manager
13	authtoken	token
14	authtoken	tokenproxy
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
26	contenttypes	0001_initial	2025-10-28 15:32:18.813321+07
27	vehicle	0001_initial	2025-10-28 15:32:18.896118+07
28	contenttypes	0002_remove_content_type_name	2025-10-28 15:32:18.906383+07
29	auth	0001_initial	2025-10-28 15:32:18.941757+07
30	auth	0002_alter_permission_name_max_length	2025-10-28 15:32:18.948492+07
31	auth	0003_alter_user_email_max_length	2025-10-28 15:32:18.960028+07
32	auth	0004_alter_user_username_opts	2025-10-28 15:32:18.971383+07
33	auth	0005_alter_user_last_login_null	2025-10-28 15:32:18.978996+07
34	auth	0006_require_contenttypes_0002	2025-10-28 15:32:18.981128+07
35	auth	0007_alter_validators_add_error_messages	2025-10-28 15:32:18.992558+07
36	auth	0008_alter_user_username_max_length	2025-10-28 15:32:19.00022+07
37	auth	0009_alter_user_last_name_max_length	2025-10-28 15:32:19.009466+07
38	auth	0010_alter_group_name_max_length	2025-10-28 15:32:19.01781+07
39	auth	0011_update_proxy_permissions	2025-10-28 15:32:19.033311+07
83	sessions	0001_initial	2025-10-28 13:00:08.277294+07
40	auth	0012_alter_user_first_name_max_length	2025-10-28 15:32:19.044594+07
41	authentication	0001_initial	2025-10-28 15:32:19.110953+07
42	admin	0001_initial	2025-10-28 15:32:19.141208+07
43	admin	0002_logentry_remove_auto_add	2025-10-28 15:32:19.152385+07
44	admin	0003_logentry_add_action_flag_choices	2025-10-28 15:32:19.16755+07
45	authentication	0002_manager_position	2025-10-28 15:32:19.188923+07
46	authentication	0003_remove_manager_position	2025-10-28 15:32:19.21014+07
47	authtoken	0001_initial	2025-10-28 15:32:19.245442+07
48	authtoken	0002_auto_20160226_1747	2025-10-28 15:32:19.329875+07
49	authtoken	0003_tokenproxy	2025-10-28 15:32:19.332721+07
50	authtoken	0004_alter_tokenproxy_options	2025-10-28 15:32:19.33889+07
51	vehicle	0002_alter_drivervehicle_driver_and_more	2025-10-28 15:32:19.384806+07
52	vehicle	0003_driver_license_categories	2025-10-28 15:32:19.393063+07
53	vehicle	0004_remove_driver_license_categories	2025-10-28 15:32:19.404538+07
24	sessions	0001_initial	2025-10-16 14:55:09.136079+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
53lb1uw3r51iras93ey8m1d2bhr5o21r	.eJxVjDsOwjAQBe_iGln-rO0NJX3OYK1_OIAcKU4qxN1JpBTQvpl5b-ZpW6vfel78lNiVSXb53QLFZ24HSA9q95nHua3LFPih8JN2Ps4pv26n-3dQqde91igKqpQpGqcsSmmCVGQFFECjBzBZYnA26uJMMiRoJzhoBAoALlj2-QK-zjbo:1vDcDJ:spqogMVRyZx4rajaIR6MKsYqPxYdMwQQjHAf1kYi5zQ	2025-11-11 12:25:45.471+07
87tk3c7f1mng0iaz3kg3cuyuxv52l3o8	.eJxVjDsOwjAQBe_iGln-rO0NJX3OYK1_OIAcKU4qxN1JpBTQvpl5b-ZpW6vfel78lNiVSXb53QLFZ24HSA9q95nHua3LFPih8JN2Ps4pv26n-3dQqde91igKqpQpGqcsSmmCVGQFFECjBzBZYnA26uJMMiRoJzhoBAoALlj2-QK-zjbo:1vD5Xh:xqzojTthkiA2QdECwSZTeBE2XEEJxbMKM9f5pL9lp3Y	2025-11-10 01:32:37.283+07
t64cjzdxgrolhafc971dpw7gwn7iowx4	.eJxVjDsOwjAQBe_iGln-rO0NJX3OYK1_OIAcKU4qxN1JpBTQvpl5b-ZpW6vfel78lNiVSXb53QLFZ24HSA9q95nHua3LFPih8JN2Ps4pv26n-3dQqde91igKqpQpGqcsSmmCVGQFFECjBzBZYnA26uJMMiRoJzhoBAoALlj2-QK-zjbo:1vDf8J:vEnzUGC8f7jdRyYbHzho3JiIQoL1V9kldcq1HAvieQk	2025-11-11 15:32:47.294759+07
\.


--
-- Data for Name: vehicle_brand; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.vehicle_brand (id, name, vehicle_type, fuel_tank_capacity, cargo_capacity, seating_capacity) FROM stdin;
1	BMW	car	78	1000	5
\.


--
-- Data for Name: vehicle_driver; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.vehicle_driver (id, first_name, last_name, license_number, salary, enterprise_id) FROM stdin;
1	Иван	Иванов	123456789	50000.00	1
2	Сергей	Сергеев	123456780	50000.00	1
3	Семён	Кузьмов	123453546	50000.00	1
4	Кирилл	Андреев	342563465	50000.00	2
5	Юрий	Петров	237594873	50000.00	2
6	Дмитрий	Цирман	476385467	50000.00	2
7	Андрей	Кириллов	457634231	50000.00	3
8	Еким	Денисов	576444343	50000.00	3
9	Тимур	Ирман	45345324	50000.00	3
\.


--
-- Data for Name: vehicle_drivervehicle; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.vehicle_drivervehicle (id, is_active, driver_id, vehicle_id) FROM stdin;
4	f	7	3
9	f	1	14
\.


--
-- Data for Name: vehicle_enterprise; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.vehicle_enterprise (id, name, city, address, phone) FROM stdin;
1	Рога и Копыта	Москва	Краснопрудная	+7 495 02-55-252
2	Русское авто	Москва	ул. Новая, д. 1	+7 (383) 123-45-67
3	Автодом	Москва	ул. Новая, д. 1	+7 (383) 123-45-67
6	Тест	Москва	Адрес	45634
15	Тест	ch	cfg	4567567
\.


--
-- Data for Name: vehicle_vehicle; Type: TABLE DATA; Schema: public; Owner: vehicleuser2
--

COPY public.vehicle_vehicle (id, car_number, price, year, mileage, fuel_type, transmission, color, created_at, brand_id, enterprise_id) FROM stdin;
3	Н234ПП	2000000.00	2024	40	gasoline	automatic	Серый	2025-10-20 04:12:32.965+07	1	3
14	ЕЕ453РН54	2000000.00	2020	1	gasoline	manual	er	2025-10-20 19:36:26.576+07	1	1
15	Е456АП	2000000.00	2025	0	electric	robot	White	2025-10-28 14:41:06.813+07	1	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: authentication_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.authentication_customuser_groups_id_seq', 1, false);


--
-- Name: authentication_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.authentication_customuser_id_seq', 5, true);


--
-- Name: authentication_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.authentication_customuser_user_permissions_id_seq', 1, false);


--
-- Name: authentication_manager_enterprises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.authentication_manager_enterprises_id_seq', 7, true);


--
-- Name: authentication_manager_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.authentication_manager_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 63, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 53, true);


--
-- Name: vehicle_driver_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.vehicle_driver_id_seq', 9, true);


--
-- Name: vehicle_drivervehicle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.vehicle_drivervehicle_id_seq', 9, true);


--
-- Name: vehicle_enterprise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.vehicle_enterprise_id_seq', 15, true);


--
-- Name: vehicle_vehicle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: vehicleuser2
--

SELECT pg_catalog.setval('public.vehicle_vehicle_id_seq', 15, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_groups authentication_customuse_customuser_id_group_id_8a637646_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuse_customuser_id_group_id_8a637646_uniq UNIQUE (customuser_id, group_id);


--
-- Name: authentication_customuser_user_permissions authentication_customuse_customuser_id_permission_923704b1_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuse_customuser_id_permission_923704b1_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: authentication_customuser_groups authentication_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_user_permissions authentication_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_username_key UNIQUE (username);


--
-- Name: authentication_manager_enterprises authentication_manager_e_manager_id_enterprise_id_8464e851_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager_enterprises
    ADD CONSTRAINT authentication_manager_e_manager_id_enterprise_id_8464e851_uniq UNIQUE (manager_id, enterprise_id);


--
-- Name: authentication_manager_enterprises authentication_manager_enterprises_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager_enterprises
    ADD CONSTRAINT authentication_manager_enterprises_pkey PRIMARY KEY (id);


--
-- Name: authentication_manager authentication_manager_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager
    ADD CONSTRAINT authentication_manager_pkey PRIMARY KEY (id);


--
-- Name: authentication_manager authentication_manager_user_id_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager
    ADD CONSTRAINT authentication_manager_user_id_key UNIQUE (user_id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: vehicle_brand vehicle_brand_name_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_brand
    ADD CONSTRAINT vehicle_brand_name_key UNIQUE (name);


--
-- Name: vehicle_brand vehicle_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_brand
    ADD CONSTRAINT vehicle_brand_pkey PRIMARY KEY (id);


--
-- Name: vehicle_driver vehicle_driver_license_number_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_driver
    ADD CONSTRAINT vehicle_driver_license_number_key UNIQUE (license_number);


--
-- Name: vehicle_driver vehicle_driver_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_driver
    ADD CONSTRAINT vehicle_driver_pkey PRIMARY KEY (id);


--
-- Name: vehicle_drivervehicle vehicle_drivervehicle_driver_id_vehicle_id_c58fdb93_uniq; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_drivervehicle
    ADD CONSTRAINT vehicle_drivervehicle_driver_id_vehicle_id_c58fdb93_uniq UNIQUE (driver_id, vehicle_id);


--
-- Name: vehicle_drivervehicle vehicle_drivervehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_drivervehicle
    ADD CONSTRAINT vehicle_drivervehicle_pkey PRIMARY KEY (id);


--
-- Name: vehicle_enterprise vehicle_enterprise_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_enterprise
    ADD CONSTRAINT vehicle_enterprise_pkey PRIMARY KEY (id);


--
-- Name: vehicle_vehicle vehicle_vehicle_car_number_key; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_vehicle
    ADD CONSTRAINT vehicle_vehicle_car_number_key UNIQUE (car_number);


--
-- Name: vehicle_vehicle vehicle_vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_vehicle
    ADD CONSTRAINT vehicle_vehicle_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_customuser__customuser_id_33d2a5f7; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_customuser__customuser_id_33d2a5f7 ON public.authentication_customuser_user_permissions USING btree (customuser_id);


--
-- Name: authentication_customuser__permission_id_e47332af; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_customuser__permission_id_e47332af ON public.authentication_customuser_user_permissions USING btree (permission_id);


--
-- Name: authentication_customuser_groups_customuser_id_a7d1343c; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_customuser_groups_customuser_id_a7d1343c ON public.authentication_customuser_groups USING btree (customuser_id);


--
-- Name: authentication_customuser_groups_group_id_c5ef1d10; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_customuser_groups_group_id_c5ef1d10 ON public.authentication_customuser_groups USING btree (group_id);


--
-- Name: authentication_customuser_username_3dffdf84_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_customuser_username_3dffdf84_like ON public.authentication_customuser USING btree (username varchar_pattern_ops);


--
-- Name: authentication_manager_enterprises_enterprise_id_ab4dd50a; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_manager_enterprises_enterprise_id_ab4dd50a ON public.authentication_manager_enterprises USING btree (enterprise_id);


--
-- Name: authentication_manager_enterprises_manager_id_7f1fe173; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authentication_manager_enterprises_manager_id_7f1fe173 ON public.authentication_manager_enterprises USING btree (manager_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: unique_active_driver; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE UNIQUE INDEX unique_active_driver ON public.vehicle_drivervehicle USING btree (driver_id) WHERE is_active;


--
-- Name: unique_active_vehicle; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE UNIQUE INDEX unique_active_vehicle ON public.vehicle_drivervehicle USING btree (vehicle_id) WHERE is_active;


--
-- Name: vehicle_brand_name_4d26e287_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_brand_name_4d26e287_like ON public.vehicle_brand USING btree (name varchar_pattern_ops);


--
-- Name: vehicle_driver_enterprise_id_5bfe2e65; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_driver_enterprise_id_5bfe2e65 ON public.vehicle_driver USING btree (enterprise_id);


--
-- Name: vehicle_driver_license_number_abf1cf3f_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_driver_license_number_abf1cf3f_like ON public.vehicle_driver USING btree (license_number varchar_pattern_ops);


--
-- Name: vehicle_drivervehicle_driver_id_4e2d5bbe; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_drivervehicle_driver_id_4e2d5bbe ON public.vehicle_drivervehicle USING btree (driver_id);


--
-- Name: vehicle_drivervehicle_vehicle_id_5806b18d; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_drivervehicle_vehicle_id_5806b18d ON public.vehicle_drivervehicle USING btree (vehicle_id);


--
-- Name: vehicle_vehicle_brand_id_38190864; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_vehicle_brand_id_38190864 ON public.vehicle_vehicle USING btree (brand_id);


--
-- Name: vehicle_vehicle_car_number_b4bd5c04_like; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_vehicle_car_number_b4bd5c04_like ON public.vehicle_vehicle USING btree (car_number varchar_pattern_ops);


--
-- Name: vehicle_vehicle_enterprise_id_c9ae82af; Type: INDEX; Schema: public; Owner: vehicleuser2
--

CREATE INDEX vehicle_vehicle_enterprise_id_c9ae82af ON public.vehicle_vehicle USING btree (enterprise_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_customuser_id_33d2a5f7_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_customuser_id_33d2a5f7_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_customuser_id_a7d1343c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_customuser_id_a7d1343c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_group_id_c5ef1d10_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_group_id_c5ef1d10_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_permission_id_e47332af_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_permission_id_e47332af_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_manager_enterprises authentication_manag_enterprise_id_ab4dd50a_fk_vehicle_e; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager_enterprises
    ADD CONSTRAINT authentication_manag_enterprise_id_ab4dd50a_fk_vehicle_e FOREIGN KEY (enterprise_id) REFERENCES public.vehicle_enterprise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_manager_enterprises authentication_manag_manager_id_7f1fe173_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager_enterprises
    ADD CONSTRAINT authentication_manag_manager_id_7f1fe173_fk_authentic FOREIGN KEY (manager_id) REFERENCES public.authentication_manager(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_manager authentication_manag_user_id_4e165710_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authentication_manager
    ADD CONSTRAINT authentication_manag_user_id_4e165710_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicle_driver vehicle_driver_enterprise_id_5bfe2e65_fk_vehicle_enterprise_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_driver
    ADD CONSTRAINT vehicle_driver_enterprise_id_5bfe2e65_fk_vehicle_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES public.vehicle_enterprise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicle_drivervehicle vehicle_drivervehicle_driver_id_4e2d5bbe_fk_vehicle_driver_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_drivervehicle
    ADD CONSTRAINT vehicle_drivervehicle_driver_id_4e2d5bbe_fk_vehicle_driver_id FOREIGN KEY (driver_id) REFERENCES public.vehicle_driver(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicle_drivervehicle vehicle_drivervehicle_vehicle_id_5806b18d_fk_vehicle_vehicle_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_drivervehicle
    ADD CONSTRAINT vehicle_drivervehicle_vehicle_id_5806b18d_fk_vehicle_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES public.vehicle_vehicle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicle_vehicle vehicle_vehicle_brand_id_38190864_fk_vehicle_brand_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_vehicle
    ADD CONSTRAINT vehicle_vehicle_brand_id_38190864_fk_vehicle_brand_id FOREIGN KEY (brand_id) REFERENCES public.vehicle_brand(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vehicle_vehicle vehicle_vehicle_enterprise_id_c9ae82af_fk_vehicle_enterprise_id; Type: FK CONSTRAINT; Schema: public; Owner: vehicleuser2
--

ALTER TABLE ONLY public.vehicle_vehicle
    ADD CONSTRAINT vehicle_vehicle_enterprise_id_c9ae82af_fk_vehicle_enterprise_id FOREIGN KEY (enterprise_id) REFERENCES public.vehicle_enterprise(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO vehicleuser2;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO vehicleuser2;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO vehicleuser2;


--
-- PostgreSQL database dump complete
--

\unrestrict 6VVB9cLz2NVNWEsefUYY9wwSxZYoPtxvtD2yThU5dvYFXsgbdwz7RmEP9HKEwhY

