# uwsgi.ini
[uwsgi]
chdir = /home/ksenia/PycharmProjects/PythonProject1
module = vehicles.wsgi:application
home = /home/ksenia/PycharmProjects/PythonProject1/.venv

socket = /home/ksenia/PycharmProjects/PythonProject1/vehicles.sock
chmod-socket = 666
; chown-socket = ksenia:www-data

master = true
processes = 3
threads = 2
vacuum = true

logto = /var/log/uwsgi/vehicles.log

# uid = ksenia
# gid = www-data

harakiri = 300
socket-timeout = 300
