# Generated by Django 5.2.5 on 2025-09-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название бренда')),
                ('vehicle_type', models.CharField(choices=[('noname', 'noname'), ('car', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('motorcycle', 'Мотоцикл')], max_length=20, verbose_name='Тип транспорта')),
                ('fuel_tank_capacity', models.PositiveSmallIntegerField(verbose_name='Объем бака, л')),
                ('cargo_capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Грузоподъемность, кг')),
                ('seating_capacity', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Номер водительского удостоверения')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата, ₽')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название предприятия')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный водитель')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='vehicle.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Назначение водителя автомобилю',
                'verbose_name_plural': 'Назначения водителей автомобилям',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vehicle.enterprise', verbose_name='Предприятие'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprises', models.ManyToManyField(related_name='managers', to='vehicle.enterprise', verbose_name='Предприятия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('car_number', models.CharField(max_length=15, unique=True, verbose_name='Государственный номер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость, ₽')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег, км')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('gas', 'Газ')], max_length=20, verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Роботизированная'), ('variator', 'Вариатор')], max_length=20, verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vehicle.brand', verbose_name='Бренд')),
                ('drivers', models.ManyToManyField(related_name='vehicle_drivers', through='vehicle.DriverVehicle', to='vehicle.driver', verbose_name='водители')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicle.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='drivervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drivers', to='vehicle.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='driver_vehicles', through='vehicle.DriverVehicle', to='vehicle.vehicle', verbose_name='автомобили'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('driver',), name='unique_active_driver'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vehicle',), name='unique_active_vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='drivervehicle',
            unique_together={('driver', 'vehicle')},
        ),
    ]
