# Generated by Django 5.2.5 on 2025-10-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_vehicles', to='vehicle.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_drivers', to='vehicle.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicle.enterprise', verbose_name='Предприятие'),
        ),
    ]
