# Generated by Django 5.2.5 on 2025-09-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='vehicle.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drivers', to='vehicle.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='vehicle.DriverVehicle', to='vehicle.driver', verbose_name='водители'),
        ),
    ]
