# Generated by Django 5.2.5 on 2025-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_drivervehicle_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_categories',
            field=models.CharField(blank=True, help_text='Например: B, C, CE', max_length=50, verbose_name='Категории прав'),
        ),
    ]
