# Generated by Django 5.2.5 on 2025-09-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_drivervehicle_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='driver_vehicles', through='vehicle.DriverVehicle', to='vehicle.vehicle', verbose_name='автомобили'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicle_drivers', through='vehicle.DriverVehicle', to='vehicle.driver', verbose_name='водители'),
        ),
    ]
