# Generated by Django 5.2.5 on 2025-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_driver_license_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_categories',
        ),
    ]
