# Generated by Django 5.2.5 on 2025-09-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_driver_enterprise_alter_vehicle_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.driver', verbose_name='водители'),
        ),
    ]
