# Generated by Django 5.2.5 on 2026-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_enterprise_timezone_vehicle_purchase_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
