# Generated by Django 5.2.5 on 2025-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_remove_driver_vehicles_remove_vehicle_drivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
