# Generated by Django 5.2.5 on 2025-08-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Государственный номер'),
        ),
    ]
