# Generated by Django 5.2.5 on 2025-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(max_length=15, verbose_name='Государственный номер'),
        ),
    ]
