# Generated by Django 5.2.5 on 2025-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Государственный номер'),
        ),
    ]
