# Generated by Django 5.2.5 on 2025-08-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, default='Нет', null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.brand', verbose_name='Бренд'),
        ),
    ]
