# Generated by Django 5.2.5 on 2026-03-22 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название отчёта')),
                ('report_type', models.CharField(choices=[('MILEAGE', 'Пробег автомобиля'), ('FUEL', 'Расход топлива'), ('TRIPS_COUNT', 'Количество поездок')], max_length=50, verbose_name='Тип отчёта')),
                ('period', models.CharField(choices=[('DAY', 'День'), ('MONTH', 'Месяц'), ('YEAR', 'Год')], default='DAY', max_length=20, verbose_name='Период')),
                ('start_date', models.DateTimeField(verbose_name='Начальная дата')),
                ('end_date', models.DateTimeField(verbose_name='Конечная дата')),
                ('vehicle_ids', models.JSONField(default=list, verbose_name='ID Автомобилей')),
                ('enterprise_id', models.IntegerField(blank=True, null=True, verbose_name='ID Предприятия')),
                ('result_data', models.JSONField(default=list, verbose_name='Результат (время-значение)')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'indexes': [models.Index(fields=['report_type', 'created_at'], name='reports_rep_report__55dc3d_idx')],
            },
        ),
    ]
