# Generated by Django 5.2.5 on 2025-10-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_manager_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='position',
        ),
    ]
