# Generated by Django 5.2.5 on 2025-12-09 19:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0005_enterprise_timezone_vehicle_purchase_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='vehicle.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', '-timestamp'], name='idx_vehicle_ts_desc')],
            },
        ),
    ]
