# Generated by Django 5.2.5 on 2025-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrypoint',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
