# Generated by Django 5.2.5 on 2026-01-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetrypoint_id'),
        ('vehicle', '0005_enterprise_timezone_vehicle_purchase_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='telemetrypoint',
            name='idx_vehicle_ts_desc',
        ),
        migrations.AlterField(
            model_name='telemetrypoint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['vehicle', 'timestamp'], name='telemetry_t_vehicle_bebced_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrypoint',
            index=models.Index(fields=['location'], name='telemetry_t_locatio_d0295d_idx'),
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_ends', to='telemetry.telemetrypoint', verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='start_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_starts', to='telemetry.telemetrypoint', verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicle.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AddIndex(
            model_name='telemetrytrip',
            index=models.Index(fields=['vehicle', 'start_point', 'end_point'], name='telemetry_t_vehicle_c7d077_idx'),
        ),
    ]
