# Generated by Django 5.2.5 on 2026-01-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetrytrip_and_more'),
        ('vehicle', '0005_enterprise_timezone_vehicle_purchase_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetrytrip',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveIndex(
            model_name='telemetrytrip',
            name='telemetry_t_vehicle_c7d077_idx',
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddIndex(
            model_name='telemetrytrip',
            index=models.Index(fields=['vehicle', 'start_time', 'end_time'], name='telemetry_t_vehicle_785f86_idx'),
        ),
    ]
