# Generated by Django 5.2.5 on 2026-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_telemetrytrip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrytrip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
