# Generated by Django 5.2.5 on 2026-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_alter_telemetrytrip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrypoint',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='telemetrytrip',
            name='guid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
