# Generated by Django 5.2.5 on 2026-03-06 18:24
from uuid import uuid4

from django.db import migrations

def populate_guids(apps, schema_editor):
    TelemetryPoint = apps.get_model('telemetry', 'TelemetryPoint')
    TelemetryTrip = apps.get_model('telemetry', 'TelemetryTrip')

    for model in [TelemetryPoint, TelemetryTrip]:
        for obj in model.objects.filter(guid__isnull=True).iterator():
            obj.guid = uuid4()
            obj.save(update_fields=['guid'])


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_telemetrypoint_guid_telemetrytrip_guid'),
    ]

    operations = [
        migrations.RunPython(populate_guids, reverse_code=migrations.RunPython.noop),
    ]
