# Generated by Django 5.2.5 on 2026-03-06 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_auto_20260306_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrypoint',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='telemetrytrip',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
